### ISSUE TITLE
Can't build releases 43-45

### ISSUE THREAD

**Issue by StephenPreston** [jeremytammik/forgefader#10]
release 43 build fails with errors about "/Users/PrestoS/Documents/Dev/forgefader-0.0.43/node_modules/Viewing.Extension.Fader doesn't exist"

For release 45, after trying to manually npm install cross-env, rifraf and webpack, I knw get this error. This doesn't seem to be a very user friendly npm package.

>>
Unhandled Rejection at: Promise  Promise {
  <rejected> { Error: Cannot find module 'inline-manifest-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/PrestoS/Documents/Dev/forgefader-0.0.45/webpack/production.webpack.config.js:7:37)
    at Module._compile (module.js:570:32)
    at loader (/Users/PrestoS/Documents/Dev/forgefader-0.0.45/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/PrestoS/Documents/Dev/forgefader-0.0.45/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) code: 'MODULE_NOT_FOUND' } }  reason:  { Error: Cannot find module 'inline-manifest-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/PrestoS/Documents/Dev/forgefader-0.0.45/webpack/production.webpack.config.js:7:37)
    at Module._compile (module.js:570:32)
    at loader (/Users/PrestoS/Documents/Dev/forgefader-0.0.45/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/PrestoS/Documents/Dev/forgefader-0.0.45/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) code: 'MODULE_NOT_FOUND' }
<<

**Comment by jeremytammik** [comment]
hi stephen, yes, i see the same issue when deploying to heroku. i have nop idea what might be causing it, nor does cyrille. it appears to be webpack related. it does not appear when deploying locally, only in heroku. @leefsmp philippe, can you please take a look? thank you!

**Comment by jeremytammik** [comment]
@StephenPreston can you build and deploy the development version locally? i have no problem at all with that. i just deleted `node_modules` and redid it from scratch to ensure it works fine.

```
cd forgefader
npm install
npm start
```

followed by 

http://localhost:3000/viewer?urn=YOUR_URN
